### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by kostaa** [pulyaevskiy/firebase-functions-interop#35]
Getting this error during the deployment. Not sure if this is a Firebase issue or the generated code is invalid. When I googled this found somewhat similar problems that were resolved by downgrading the Firebase tools versions. 

![image](https://user-images.githubusercontent.com/7585117/47266916-9f27c700-d534-11e8-9bd7-d3990c93ee0e.png)

These are two functions that I am deploying. However when I remove the 'applySystemPayeeRules' method and the dependency on the the library where this is implemented all is good. So this makes me think that maybe the generated code is not quite right.

![image](https://user-images.githubusercontent.com/7585117/47266969-6e945d00-d535-11e8-8e05-2bed0113a58b.png)

Here is the 'index.dart.js' if that helps. 
[index.dart.js.zip](https://github.com/pulyaevskiy/firebase-functions-interop/files/2499120/index.dart.js.zip)

**Comment by pulyaevskiy** [comment]
Could you also provide following?

1. Dart SDK version (`dart --version`)
2. Node.js version (`node --version`)
2. Firebase tools version (`firebase --version`)
3. Contents of `package.json`
4. Contents of `pubspec.yaml`

This would help in investigating your issue.

**Comment by kostaa** [comment]
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"
Node version: v8.12.0
Firebase version: 5.1.1

```
package.json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5"
  },
  "private": true,
  "main": "build/node/index.dart.js"
}
```

```
pubspec.yaml

name: mv_cloud_functions
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0-dev
  system_payee_rules:
    path: ../lib_sys_payee_rules

dev_dependencies:
  build_node_compilers: any
  build_runner: any
  test: any
```
These are the actual versions 

firebase_functions_interop: "1.0.0-dev.10.0"
build_node_compilers: "0.2.0"
build_runner: "1.0.0"
