### ISSUE TITLE
Can't import firebase_functions_interop.dart

### ISSUE THREAD

**Issue by tumbling-dice** [pulyaevskiy/firebase-functions-interop#42]
I created a project with reference to the README, but I can't import `package:firebase_functions_interop/firebase_functions_interop.dart`.

index.dart:
![screenshot](https://user-images.githubusercontent.com/7441093/48969740-4e7d1f80-f046-11e8-8128-c51c7d88d14b.jpg)

pubspec.yaml:
```yaml
name: firebase_functions_test
description: test.
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  firebase_functions_interop: ^1.0.0-dev

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
```
