### ISSUE TITLE
Is this being deprecated?

### ISSUE THREAD

**Issue by alfinbi** [pulyaevskiy/firebase-functions-interop#69]
Is this package being deprecated?
I haven't see any update for almost a year.

**Comment by Semapl3** [comment]
I use it with firebase_admin_interop: ^2.1.0 (for this you need to fork and replace the dependency)

There is a fork for firebase_admin_interop: ^2.1.0:
https://github.com/Skquark/firebase-functions-interop

```
firebase_functions_interop:
    git:
      url: git://github.com/Skquark/firebase-functions-interop

firebase_admin_interop: ^2.1.0
```

All this can be run on: Flutter - stable, v1.12.13+hotfix.9
To write Firebase functions is enough.
There are some problems in newer versions.
